service:
    data:
        schemas:
        -
            type: pipeline
            properties:
                name:
                    type: string
                    hash: true
                description:
                    type: string
                updatedon:
                    type: long
                createdon:
                    type: long
                createdby:
                    type: string
                updatedby:
                    type: string
                workflow:
                    type: map
            constraints:
                unique: 
                    - name
                notnull:
                    - name
                    - description
            rules:
                name:
                    length:
                        min: 3
                        max: 100
                description:
                    length:
                        min: 5
                        max: 250
            defaults:
                updatedon:
                    value: $timestamp
                    override: true
                createdon:
                    value: $timestamp
                createdby:
                    value: $loggedinuser
                updatedby:
                    value: $loggedinuser
                    override: true
            index:
                - name